config/routes.rb
Ponto::Application.routes.draw do
  resources :users

  resources :justifications

  resources :departments

  resources :employees do
    collection do
      get "get_office_hours"
      get "get_departments"
    end
    member do
      get "replicate"
    end
  end

  resources :enterprises

  resources :holidays

  resources :office_hours

  resources :reports do

    collection do
      get "filter_ficha_ponto"
      get "ficha_ponto"
    end
  end

  resources :roles

  resources :points do
    collection do
      get  'process_points'
      post 'save_fingerprint'
    end
  end
  
  resource :session, controller: 'sessions'
  
  match 'sign_in' => 'sessions#new', :as => 'sign_in'

  root :to => 'home#index'

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  belongs_to :enterprise, :class_name => "Enterprise", :foreign_key => "enterprise_id"
	validates_presence_of :name
	validates_presence_of :date

	scope :by_name, lambda {|parameter| where("upper(name) like upper(?)", "%#{parameter}%")}
	scope :by_start_date, lambda {|parameter| where("date >= ?",  Date.parse(parameter).strftime('%Y-%m-%d'))}
	scope :by_end_date, lambda {|parameter| where("date <= ?",  Date.parse(parameter).strftime('%Y-%m-%d'))}

	def self.holiday?(enterprise_id, date)
		Holiday.where("date = ? and (enterprise_id is null or enterprise_id = ?)", date.strftime('%Y-%m-%d'), enterprise_id).first
	end

end

app/controllers/holidays_controller.rb
class HolidaysController < InheritedResources::Base
  load_and_authorize_resource
	has_scope :by_name
	has_scope :by_start_date
	has_scope :by_end_date

  def index
    @holidays = apply_scopes(Holiday).all
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= simple_form_for(@holiday) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.association :enterprise, :label_method =>"name", :include_blank => true %>
    <%= f.input :name %>
    <%= f.input :date, :as => :string, :input_html => { :class => 'datepicker', :value => @holiday.date.nil? ? "" : @holiday.date.strftime('%d/%m/%Y')} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Salvar" %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editar feriado</h1>

<%= render 'form' %>

<%= link_to 'Mostar', @holiday %> |
<%= link_to 'Voltar', holidays_path %>

app/views/holidays/index.html.erb
<h1>Lista de feriados</h1>
<br>
<%= form_tag holidays_path, :method => :get, :class => "well form-inline"  do -%>
  <label>Nome</label>
  <%= text_field_tag :by_name, params[:by_name] %>
  <label>Período</label>
  <%= text_field_tag :by_start_date, params[:by_start_date], :class => "datepicker" %>
  <%= text_field_tag :by_end_date, params[:by_end_date], :class => "datepicker" %>
  <button type="submit" class="btn"><i class="icon-search"></i></button>
<% end -%>

<table class="table table-bordered table-striped">
  <tr>
    <th>Nome</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @holidays.each do |holiday| %>
  <tr>
    <td><%= holiday.name %></td>
    <td><%= holiday.date.strftime('%d/%m/%Y') %></td>
    <td><%= link_to raw("<i class='icon-folder-open'></i>"), holiday, :class => "btn btn-mini", :title => "Mostar" %></td>
    <td><%= link_to raw("<i class='icon-pencil'></i>"), edit_holiday_path(holiday), :class => "btn btn-mini", :title => "Editar" %></td>
    <td><%= link_to raw("<i class='icon-remove-sign'></i>"), holiday, confirm: 'Tem certeza?', method: :delete, :class => "btn btn-mini", :title => "Excluir" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to raw("<i class='icon-file'></i>Adicionar"), new_holiday_path, :class => "btn", :title => "Adicionar" %>

app/views/holidays/new.html.erb
<h1>Novo feriado</h1>

<%= render 'form' %>

<%= link_to 'Voltar', holidays_path %>

app/views/holidays/show.html.erb
<p>
  <b>Nome:</b>
  <%= @holiday.name %>
</p>

<p>
  <b>Data:</b>
  <%= @holiday.date.strftime('%d/%m/%Y') %>
</p>


<%= link_to 'Editar', edit_holiday_path(@holiday) %> |
<%= link_to 'Voltar', holidays_path %>