config/routes.rb
Ponto::Application.routes.draw do
  resources :users

  resources :justifications

  resources :departments

  resources :employees do
    collection do
      get "get_office_hours"
      get "get_departments"
    end
    member do
      get "replicate"
    end
  end

  resources :enterprises

  resources :holidays

  resources :office_hours

  resources :reports do

    collection do
      get "filter_ficha_ponto"
      get "ficha_ponto"
    end
  end

  resources :roles

  resources :points do
    collection do
      get  'process_points'
      post 'save_fingerprint'
    end
  end
  
  resource :session, controller: 'sessions'
  
  match 'sign_in' => 'sessions#new', :as => 'sign_in'

  root :to => 'home#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :enterprise, :class_name => "Enterprise", :foreign_key => "enterprise_id"
  belongs_to :role, :class_name => "Role", :foreign_key => "role_id"
  belongs_to :department, :class_name => "Department", :foreign_key => "department_id"
  belongs_to :office_hour, :class_name => "OfficeHour", :foreign_key => "office_hour_id"
  has_many :points, :class_name => "Point", :foreign_key => "employee_id"
  has_many :currentpoints, :class_name => "Point", :foreign_key => "employee_id",
           :conditions => lambda {|parameter| "date between '#{date1}' and '#{date2}'"}

  attr_accessor :date1
  attr_accessor :date2
  attr_accessor :delay
  attr_accessor :extra
  attr_accessor :faults
  attr_accessor :delay_number

  scope :by_name, lambda {|parameter| where("upper(name) like upper(?)", "%#{parameter}%")}

  validates_presence_of :name
  validates_presence_of :registry
  validates_presence_of :enterprise_id
  validates_presence_of :office_hour_id

  validates_uniqueness_of :registry

  after_initialize :init
  def init
    self.status  ||= 1
  end

  def self.save_fingerprint(registry, fingerprint)
    employee = Employee.find_by_registry(registry)
    if employee.nil?
    -1
    else
    employee.fingerprint = fingerprint
    employee.save
    1
    end
  end

  def self.migrate_employee(employee_id)
    employee = Employee.find(employee_id)
    puts employee.name
    databases = Database.all
    databases.each do |database|
      puts database.name.to_sym
      employee_slave = Employee.using(database.name.to_sym).where(:registry => employee.registry).first
      if employee_slave.nil?
        puts "Nao encontrado"

        employee_slave = Employee.using(database.name.to_sym).create(:name => employee.name,
        :registry => employee.registry,
        :fingerprint => employee.fingerprint,
        :enterprise_id => employee.enterprise_id,
        :office_hour_id => employee.office_hour_id)

      else
        puts employee_slave.name
        #employee_slave.name = employee.name
        #employee_slave.fingerprint = employee.fingerprint
        #employee_slave.registry = employee.registry
        #employee_slave.save
        employee_slave.update_attributes(:name => employee.name,
        :registry => employee.registry,
        :fingerprint => employee.fingerprint,
        :enterprise_id => employee.enterprise_id,
        :office_hour_id => employee.office_hour_id)
        puts "Encontrado"
      end

    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < InheritedResources::Base
  load_and_authorize_resource
	respond_to :html, :xml, :json, :pdf

  has_scope :by_name

  def index
    @employees = apply_scopes(Employee).all
  end
  
  def new
    @employee = Employee.new
    @departments = []
    @office_hours = []
  end
  
  def edit
    @employee = Employee.find(params[:id])
    @departments = Department.find_all_by_enterprise_id(@employee.enterprise_id)
    @office_hours = OfficeHour.find_all_by_enterprise_id(@employee.enterprise_id)
  end
  
  def get_departments
    @departments = Department.find_all_by_enterprise_id(params[:enterprise_id])
    if @departments.empty?
      @departments = []
    end 
    render :json => @departments.to_json(:only => [:id, :name]) 
  end
  
  def get_office_hours
    @office_hours = OfficeHour.find_all_by_enterprise_id(params[:enterprise_id])
    if @office_hours.empty?
      @office_hours = []
    end
    render :json => @office_hours.to_json(:only => [:id, :name])
  end
  
  def replicate
    Employee.migrate_employee(params[:id])
    redirect_to(employees_path, :notice => "Colaborador replicado com sucesso") 
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<script>
	function fingerprint(fg) {
		$('#employee_fingerprint').val(fg);
		return false;
	}

	function load_others_collections() {
		var id = $('#employee_enterprise_id :selected').val();
		$.getJSON("/employees/get_departments?enterprise_id="+id, id, function(j) {
			var options = '<option value=""></option>';
			$.each(j, function(i, item) {
				options += '<option value="' + item.id + '">' + item.name + '</option>';
			});
			$("#employee_department_id").html(options);
		});
		$.getJSON("/employees/get_office_hours?enterprise_id="+id, id, function(j) {
			var options = '<option value=""></option>';
			$.each(j, function(i, item) {
				options += '<option value="' + item.id + '">' + item.name + '</option>';
			});
			$("#employee_office_hour_id").html(options);
		});
		return false;
	}

	$(function() {

		$("#employee_cpf").mask("999.999.999-99");
		$("#employee_phone").mask("(99) 9999-9999");
		$("#employee_cel_phone").mask("(99) 9999-9999");
		$("#employee_address_zip_code").mask("99.999-999");
	});
</script>

<%= simple_form_for(@employee) do |f| %>
<%= f.error_notification %>
<%= f.input :fingerprint, :as => :hidden %>
<div class="form-inputs">
	<ul class="nav nav-tabs">
		<li class="active">
			<a href="#tab1" data-toggle="tab">Dados gerais</a>
		</li>
		<li>
			<a href="#tab2" data-toggle="tab">Documentos</a>
		</li>
		<li>
			<a href="#tab3" data-toggle="tab">Endereço</a>
		</li>
		<li>
			<a href="#tab4" data-toggle="tab">Digital</a>
		</li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab1">
			<div class="row">
				<div class="span2">
					<%= f.input :registry, :input_html => { :class => 'span2' }%>
				</div>
				<div class="span6">
					<%= f.input :name, :input_html => { :class => 'span6' }%>
				</div>
				<div class="span4">
					<%= f.association :enterprise, :label_method => :name, :input_html => { :class => 'span4' }%>
				</div>
			</div>
			<div class="row">
				<div class="span4">
					<div id="combo_office_hour">
						<%= f.association :office_hour, :collection => OfficeHour.all(:order => 'name'), :label_method => :name, :input_html => { :class => 'span4' }%>
					</div>
				</div>
				<div class="span4">
					<div id="combo_department">
						<%= f.association :department, :collection => Department.all(:order => 'name'), :label_method => :name, :input_html => { :class => 'span4' }%>
					</div>
				</div>
				<div class="span4">
					<%= f.association :role, :label_method => :description, :input_html => { :class => 'span4' }%>
				</div>
			</div>
			<div class="row">
				<div class="span2">
					<%= f.input :date_of_admission, :as => :string, :input_html => { :class => 'span2 datepicker' }%>
				</div>
				<div class="span2">
					<%= f.input :sex, :collection => ['F', 'M'], :input_html => { :class => 'span2' }%>
				</div>
				<div class="span2">
					<%= f.input :password, :input_html => { :class => 'span2' }%>
				</div>
				<div class="span2">
					<%= f.input :date_of_birth, :as => :string, :input_html => { :class => 'span2 datepicker' }%>
				</div>
				<div class="span2">
					<%= f.input :status, :collection => Status::STATUS_LIST, :input_html => { :class => 'span2' }%>
				</div>
			</div>
			<div class="row">
				<div class="span6">
					<%= f.input :email, :input_html => { :class => 'span6' }%>
				</div>
				<div class="span3">
					<%= f.input :phone, :input_html => { :class => 'span3' }%>
				</div>
				<div class="span3">
					<%= f.input :cel_phone, :input_html => { :class => 'span3' }%>
				</div>
			</div>
			<div class="row">
				<div class="span12">
					<%= f.input :obs, :input_html => { :class => 'span12' }%>
				</div>
			</div>
		</div>
		<div class="tab-pane" id="tab2">
			<%= f.input :cpf %>
			<div class="row">
				<div class="span4">
					<%= f.input :rg_number, :input_html => { :class => 'span4' }%>
				</div>
				<div class="span4">
					<%= f.input :rg_issue_date, :as => :string, :input_html => { :class => 'span4 datepicker' }%>
				</div>
				<div class="span4">
					<%= f.input :rg_issuing, :input_html => { :class => 'span4' }%>
				</div>
			</div>
			<div class="row">
				<div class="span4">
					<%= f.input :nit_pis_pasep, :input_html => { :class => 'span4' }%>
				</div>
				<div class="span4">
					<%= f.input :ctps_number, :input_html => { :class => 'span4' }%>
				</div>
				<div class="span2">
					<%= f.input :cpts_series, :input_html => { :class => 'span2' }%>
				</div>
				<div class="span2">
					<%= f.input :cpts_uf, :input_html => { :class => 'span2' }%>
				</div>
			</div>
		</div>
		<div class="tab-pane" id="tab3">
			<div class="row">
				<div class="span6">
					<%= f.input :address, :input_html => { :class => 'span6' } %>
				</div>
				<div class="span2">
					<%= f.input :address_number, :input_html => { :class => 'span2' } %>
				</div>
				<div class="span4">
					<%= f.input :address_complement, :input_html => { :class => 'span4' } %>
				</div>
			</div>
			<div class="row">
				<div class="span4">
					<%= f.input :address_neighborhood, :input_html => { :class => 'span4' } %>
				</div>
				<div class="span2">
					<%= f.input :address_zip_code, :input_html => { :class => 'span2' } %>
				</div>
				<div class="span4">
					<%= f.input :address_city, :input_html => { :class => 'span4' } %>
				</div>
				<div class="span2">
					<%= f.input :adress_state, :input_html => { :class => 'span2' } %>
				</div>
			</div>
		</div>
      <div class="tab-pane" id="tab4">
        <!-- <% if @employee.new_record? %>
          <applet code="br/gov/ce/ipmfor/sgp/FormMain.class" archive="/sgp-digitalpersona-applet-enrollment-new.jar" width="400" height="450">Seu browser não suporta applets
          </applet>
          <% else %>
          <applet code="br/gov/ce/ipmfor/sgp/FormMain.class" archive="/sgp-digitalpersona-applet-enrollment-edit.jar" width="400" height="450">	Seu browser não suporta applets
          </applet>
        -->
      <% end %>
		</div>
	</div>
</div>

<div class="form-actions">
	<%= f.button :submit, "Salvar" %>
</div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editar colaborador</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @employee %> |
<%= link_to 'Voltar', employees_path %>

app/views/employees/index.html.erb
<h1>Lista de colaboradores</h1>

<%= form_tag employees_path, :method => :get, :class => "well form-inline"  do -%>
  <label>Nome</label>
  <%= text_field_tag :by_name, params[:by_name] %>
  <button type="submit" class="btn"><i class="icon-search"></i></button>
<% end -%>

<table class="table table-bordered table-striped">
  <tr>
    <th>Nome</th>
    <th>Matrícula</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= employee.registry %></td>
    <td><%= link_to raw("<i class='icon-folder-open'></i>"), employee, :class => "btn btn-mini", :title => "Mostar" %></td>
    <td><%= link_to raw("<i class='icon-pencil'></i>"), edit_employee_path(employee), :class => "btn btn-mini", :title => "Editar" %></td>
    <td><%= link_to raw("<i class='icon-remove-sign'></i>"), employee, confirm: 'Tem certeza?', method: :delete, :class => "btn btn-mini", :title => "Excluir" %></td>
    <td><%= link_to raw("<i class='icon-repeat'></i>"), replicate_employee_path(employee),  :class => "btn btn-mini", :title => "Replicar" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to raw("<i class='icon-file'></i>Adicionar"), new_employee_path, :class => "btn", :title => "Adicionar" %>

app/views/employees/new.html.erb
<h1>Novo colaborador</h1>

<%= render 'form' %>

<%= link_to 'Voltar', employees_path %>

app/views/employees/show.html.erb
<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>


<%= link_to 'Editar', edit_employee_path(@employee) %> |
<%= link_to 'Voltar', employees_path %>