config/routes.rb
Ponto::Application.routes.draw do
  resources :users

  resources :justifications

  resources :departments

  resources :employees do
    collection do
      get "get_office_hours"
      get "get_departments"
    end
    member do
      get "replicate"
    end
  end

  resources :enterprises

  resources :holidays

  resources :office_hours

  resources :reports do

    collection do
      get "filter_ficha_ponto"
      get "ficha_ponto"
    end
  end

  resources :roles

  resources :points do
    collection do
      get  'process_points'
      post 'save_fingerprint'
    end
  end
  
  resource :session, controller: 'sessions'
  
  match 'sign_in' => 'sessions#new', :as => 'sign_in'

  root :to => 'home#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  #load_and_authorize_resource
  respond_to :html, :xml, :pdf
 

  def index
    @employees = Employee.find(:all) #apply_scopes(Employee).all
    respond_with @employees, :include => [ :points]
  end

  def filter_ficha_ponto
    if current_user.role == 4
      redirect_to(root_path, :notice => "Acesso nao permitido")
    end
  end

  def ficha_ponto
    date1 = params[:date_start].to_date.strftime("%Y-%m-%d")
    date2 = params[:date_end].to_date.strftime("%Y-%m-%d")
    if params[:by_employee_id].nil?
      @employees = Employee.where("enterprise_id = ? and department_id = ?", params[:by_enterprise], params[:by_department])
    else
      @employees = Employee.where("id = ?", params[:by_employee_id])
    end
    @employees.each do |e|
      e.date1 = date1
      e.date2 = date2
      e.delay, e.delay_number, e.extra, e.faults = Point.total_delay_extra(e.id, params[:date_start].to_date, params[:date_end].to_date)
    end

    respond_with @employees, :methods => [:delay, :delay_number, :extra, :faults], :include => [:role, :department, :currentpoints]
    
    
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/filter_ficha_ponto.html.erb
<script>
	function load_others_collections() {
		var id = $('#by_enterprise :selected').val();
		$.getJSON("/employees/get_departments?enterprise_id=" + id, id, function(j) {
			var options = '<option value=""></option>';
			$.each(j, function(i, item) {
				options += '<option value="' + item.id + '">' + item.name + '</option>';
			});
			$("#by_department").html(options);
		});
		return false;
	}

	$(function() {
		$('#fp_form').submit(function() {
			var employee = $('#by_employee_id :selected').val();
			var enterprise = $('#by_enterprise :selected').val();
			var department = $('#by_department :selected').val();
			var date_start = $('#date_start').val();
			var date_end = $('#date_end').val();
			var by_employee = $('#by_employee').val();
			if (by_employee == 'true') {
				location.href = "/reports/ficha_ponto.pdf?by_employee_id=" + employee + "&date_start=" + date_start + "&date_end=" + date_end;
			}else{
				location.href = "/reports/ficha_ponto.pdf?by_enterprise=" + enterprise + "&by_department=" + department + "&date_start=" + date_start + "&date_end=" + date_end;
			};
			return false;
		});
	}); 
</script>
<%= form_tag ficha_ponto_reports_path, :remote => true, :multipart=>true, :format => :pdf, :method => :get, :class => "well", :id => "fp_form"  do -%>
<%= hidden_field_tag :by_employee, params[:by_employee]%>

<% if params[:by_employee] =='true' %>
<label>Colaborador</label>
<%= select_tag :by_employee_id, options_from_collection_for_select(Employee.order("name").all, "id", "name", params[:by_employee_id]), :include_blank => true   %>
<% else %>
<label>Empresa</label>
<%= select_tag :by_enterprise, options_from_collection_for_select(Enterprise.order("name").all, "id", "name", params[:by_enterprise]), :include_blank => true, :onChange => "load_others_collections()"   %>

<label>Departamento</label>
<%= select_tag :by_department,[]  %>
<% end %>
<label>Data inicial</label>
<%= text_field_tag :date_start, '', :class => "datepicker" %>

<label>Data final</label>
<%= text_field_tag :date_end, '', :class => "datepicker" %>

<button type="submit" class="btn">
	<i class="icon-search"></i>
</button>

<% end -%>

app/views/reports/index.html.erb
<h1>Lista de colaboradores</h1>

<%= form_tag employees_path, :method => :get, :class => "well form-inline"  do -%>
  <label>Nome</label>
  <%= text_field_tag :by_name, params[:by_name] %>
  <button type="submit" class="btn"><i class="icon-search"></i></button>
<% end -%>

<table class="table table-bordered table-striped">
  <tr>
    <th>Nome</th>
    <th>Matrícula</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= employee.registry %></td>
    <td><%= link_to raw("<i class='icon-folder-open'></i>"), employee, :class => "btn btn-mini", :title => "Mostar" %></td>
    <td><%= link_to raw("<i class='icon-pencil'></i>"), edit_employee_path(employee), :class => "btn btn-mini", :title => "Editar" %></td>
    <td><%= link_to raw("<i class='icon-remove-sign'></i>"), employee, confirm: 'Tem certeza?', method: :delete, :class => "btn btn-mini", :title => "Excluir" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to raw("<i class='icon-file'></i>Adicionar"), new_employee_path, :class => "btn", :title => "Adicionar" %>