config/routes.rb
Ponto::Application.routes.draw do
  resources :users

  resources :justifications

  resources :departments

  resources :employees do
    collection do
      get "get_office_hours"
      get "get_departments"
    end
    member do
      get "replicate"
    end
  end

  resources :enterprises

  resources :holidays

  resources :office_hours

  resources :reports do

    collection do
      get "filter_ficha_ponto"
      get "ficha_ponto"
    end
  end

  resources :roles

  resources :points do
    collection do
      get  'process_points'
      post 'save_fingerprint'
    end
  end
  
  resource :session, controller: 'sessions'
  
  match 'sign_in' => 'sessions#new', :as => 'sign_in'

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Ponto</title>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<style>
			body {
				padding-left: 10px;
				padding-right: 10px;
			}
		</style>
	</head>
	<body>
		<% if signed_in? -%>
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">
					<%= link_to "Sistema de ponto", root_path, :class => "brand"%>
					<ul class="nav">
						<li class="dropdown" id="menu1">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#menu1"> Cadastros <b class="caret"></b> </a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to "Cargos", roles_path%>
								</li>
								<li>
									<%= link_to "Colaboradores", employees_path%>
								</li>
								<li>
									<%= link_to "Empresas", enterprises_path%>
								</li>
								<li>
									<%= link_to "Departamentos", departments_path%>
								</li>
								<li>
									<%= link_to "Feriados", holidays_path%>
								</li>
								<li>
									<%= link_to "Horários de trabalho", office_hours_path%>
								</li>
								<li>
									<%= link_to "Justificativas", justifications_path%>
								</li>
								<li>
									<%= link_to "Usuários", users_path%>
								</li>
							</ul>
						</li>
						<li class="dropdown" id="menu2">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#menu2"> Ponto <b class="caret"></b> </a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to "Manutenção", points_path%>
								</li>
								<li>
									<%= link_to "Processar ponto", process_points_points_path%>
								</li>
								<li>
									<%= link_to "Registro de ponto", new_point_path%>
								</li>
							</ul>
						</li>
						<li class="dropdown" id="menu3">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#menu3"> Relatorios <b class="caret"></b> </a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to "Ficha de ponto - por colaborador", filter_ficha_ponto_reports_path(:by_employee => true)%>
								</li>
								<li>
									<%= link_to "Ficha de ponto - por departamento", filter_ficha_ponto_reports_path(:by_employee => false)%>
								</li>
							</ul>
						</li>
					</ul>
					<ul class="nav pull-right">
						<li>
							<%= link_to current_user.username, '#' %>
						</li>
						<li class="divider-vertical"></li>
						<li>
							<%= link_to "Sair", sign_out_path, :method => :delete %>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<% end -%>
		<% if notice %>
		<div class="alert alert-success fade in" data-alert="alert">
			<a class="close" data-dismiss='alert' href="#">×</a>
			<p>
				<%= notice %>
			</p>
		</div>
		<% end %>
		<%= yield %>
	</body>
</html>

app/views/layouts/login.html.erb
            <%= yield%>